/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Choice;
import java.awt.Color;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.TextField;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author aryuska
 */
public class AdminView extends javax.swing.JFrame {

    public JPanel getSave() {
        return save;
    }

    /**
     * Creates new form AdminView
     */
    private String kapasitas;

    public JScrollPane getScroll() {
        return scroll;
    }
    private final JFileChooser openFile;

    public JPanel getjPanelItem() {
        return jPanelItem;
    }
    private BufferedImage originalBI1;
    private BufferedImage originalBI2;
    private BufferedImage originalBI3;
    private File image1;
    private File image2;
    private File image3;
    private JScrollPane scroll;

    public AdminView() {
        initComponents();
        listCC();
        listMerk();
        DaftarKendaraan.setVisible(true);
        ListKendaraan.setVisible(false);
        DaftarKendaraanSukses.setVisible(false);
        openFile = new JFileChooser();
        openFile.setFileFilter(new FileNameExtensionFilter("Image", "jpeg", "png", "jpg"));

        save.setName("saveBtn");
        nextDaftarBtn.setName("nextDaftarBtn");
        search.setName("searchBtn");

        CardLayout cl = new CardLayout();
        cl.setVgap(0);
        cl.setHgap(0);
        listPanel.setLayout(cl);
        jPanelItem.setLayout(new GridBagLayout());

        scroll = new JScrollPane(jPanelItem);
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        listPanel.add(scroll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabMenu = new javax.swing.JPanel();
        daftarKendaraan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        updateKendaraan = new javax.swing.JPanel();
        riwataRentalTxt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        DaftarKendaraanSukses = new javax.swing.JPanel();
        titleDaftarSukses = new javax.swing.JLabel();
        subTitleDaftarSukses = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        textDaftarSukses = new javax.swing.JLabel();
        subTextDaftarSukses = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        subText1 = new javax.swing.JLabel();
        subText2 = new javax.swing.JLabel();
        nextDaftarBtn = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ListKendaraan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        searchField = new javax.swing.JTextField();
        search = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        jPanelItem = new javax.swing.JPanel();
        DaftarKendaraan = new javax.swing.JPanel();
        titleFormKendaraan = new javax.swing.JLabel();
        subTitleFormKendaraan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label1 = new java.awt.Label();
        namaKendaraan = new java.awt.TextField();
        label2 = new java.awt.Label();
        merkKendaraan = new java.awt.Choice();
        label3 = new java.awt.Label();
        warnaKendaraan = new java.awt.TextField();
        label8 = new java.awt.Label();
        ccKendaraan = new java.awt.Choice();
        label9 = new java.awt.Label();
        jSeparator3 = new javax.swing.JSeparator();
        label4 = new java.awt.Label();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        hargaKendaraan = new java.awt.TextField();
        label7 = new java.awt.Label();
        kapasitas2 = new javax.swing.JPanel();
        label2org = new javax.swing.JLabel();
        kapasitas4 = new javax.swing.JPanel();
        label4org = new javax.swing.JLabel();
        kapasitas6 = new javax.swing.JPanel();
        label6org = new javax.swing.JLabel();
        save = new javax.swing.JPanel();
        textBtnFormKendaraan = new javax.swing.JLabel();
        iconArrowFormKendaraan = new javax.swing.JLabel();
        idKendaraan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabMenu.setBackground(new java.awt.Color(0, 63, 130));

        daftarKendaraan.setBackground(new java.awt.Color(0, 43, 130));
        daftarKendaraan.setPreferredSize(new java.awt.Dimension(323, 64));
        daftarKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarKendaraanMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Mulish", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 216, 82));
        jLabel10.setText("Daftar Kendaraan");

        javax.swing.GroupLayout daftarKendaraanLayout = new javax.swing.GroupLayout(daftarKendaraan);
        daftarKendaraan.setLayout(daftarKendaraanLayout);
        daftarKendaraanLayout.setHorizontalGroup(
            daftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarKendaraanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        daftarKendaraanLayout.setVerticalGroup(
            daftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftarKendaraanLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18))
        );

        updateKendaraan.setBackground(new java.awt.Color(0, 63, 130));
        updateKendaraan.setPreferredSize(new java.awt.Dimension(323, 64));
        updateKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateKendaraanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateKendaraanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateKendaraanMouseExited(evt);
            }
        });

        riwataRentalTxt.setFont(new java.awt.Font("Mulish", 1, 20)); // NOI18N
        riwataRentalTxt.setForeground(new java.awt.Color(255, 255, 255));
        riwataRentalTxt.setText("Update Kendaraan");
        riwataRentalTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwataRentalTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout updateKendaraanLayout = new javax.swing.GroupLayout(updateKendaraan);
        updateKendaraan.setLayout(updateKendaraanLayout);
        updateKendaraanLayout.setHorizontalGroup(
            updateKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateKendaraanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(riwataRentalTxt)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        updateKendaraanLayout.setVerticalGroup(
            updateKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateKendaraanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(riwataRentalTxt)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setPreferredSize(new java.awt.Dimension(239, 56));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Mulish", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(165, 0, 0));
        jLabel13.setText("Keluar");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(67, 67, 67))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(16, 16, 16))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Line 29.png"))); // NOI18N

        username.setFont(new java.awt.Font("Mulish", 1, 22)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));

        email.setFont(new java.awt.Font("Mulish Medium", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(102, 140, 180));

        pp.setPreferredSize(new java.awt.Dimension(56, 56));

        javax.swing.GroupLayout TabMenuLayout = new javax.swing.GroupLayout(TabMenu);
        TabMenu.setLayout(TabMenuLayout);
        TabMenuLayout.setHorizontalGroup(
            TabMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(daftarKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(updateKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(TabMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11))
            .addGroup(TabMenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(TabMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabMenuLayout.createSequentialGroup()
                        .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(TabMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username)
                            .addComponent(email)))
                    .addComponent(jLabel14)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        TabMenuLayout.setVerticalGroup(
            TabMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(81, 81, 81)
                .addComponent(daftarKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(updateKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(TabMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabMenuLayout.createSequentialGroup()
                        .addComponent(username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email))
                    .addComponent(pp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        DaftarKendaraanSukses.setBackground(new java.awt.Color(255, 255, 255));

        titleDaftarSukses.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titleDaftarSukses.setText("Daftar Kendaraan");

        subTitleDaftarSukses.setText("Harap isi beberapa form berikut untuk mendaftarkan kendaraan");

        textDaftarSukses.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        textDaftarSukses.setText("Pendaftaran Kendaraan Berhasil !");

        subTextDaftarSukses.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        subTextDaftarSukses.setText("kendaraan telah berhasil didaftarkan dan akan siap untuk direntalkan");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sukses.png"))); // NOI18N

        subText1.setText("Kamu dapat menyunting data dan informasi dari kendaraan yang telah ");

        subText2.setText("kamu daftarkan dengan menuju tombol dibawah");

        nextDaftarBtn.setBackground(new java.awt.Color(0, 61, 127));
        nextDaftarBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Lihat Informasi Kendaraan");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Arrow.png"))); // NOI18N

        javax.swing.GroupLayout nextDaftarBtnLayout = new javax.swing.GroupLayout(nextDaftarBtn);
        nextDaftarBtn.setLayout(nextDaftarBtnLayout);
        nextDaftarBtnLayout.setHorizontalGroup(
            nextDaftarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextDaftarBtnLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nextDaftarBtnLayout.setVerticalGroup(
            nextDaftarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextDaftarBtnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(nextDaftarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DaftarKendaraanSuksesLayout = new javax.swing.GroupLayout(DaftarKendaraanSukses);
        DaftarKendaraanSukses.setLayout(DaftarKendaraanSuksesLayout);
        DaftarKendaraanSuksesLayout.setHorizontalGroup(
            DaftarKendaraanSuksesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                .addGroup(DaftarKendaraanSuksesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(DaftarKendaraanSuksesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subTitleDaftarSukses, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleDaftarSukses)))
                    .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(textDaftarSukses)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                .addGroup(DaftarKendaraanSuksesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(subTextDaftarSukses, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel17))
                    .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(subText1))
                    .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addGroup(DaftarKendaraanSuksesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextDaftarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subText2))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DaftarKendaraanSuksesLayout.setVerticalGroup(
            DaftarKendaraanSuksesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarKendaraanSuksesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleDaftarSukses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTitleDaftarSukses)
                .addGap(24, 24, 24)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDaftarSukses, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTextDaftarSukses, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subText1)
                .addGap(18, 18, 18)
                .addComponent(subText2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextDaftarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        ListKendaraan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("Update Kendaraan");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Sunting dan edit item kendaraan yang telah didaftarkan");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 61, 127));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanelItem.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelItemLayout = new javax.swing.GroupLayout(jPanelItem);
        jPanelItem.setLayout(jPanelItemLayout);
        jPanelItemLayout.setHorizontalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelItemLayout.setVerticalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ListKendaraanLayout = new javax.swing.GroupLayout(ListKendaraan);
        ListKendaraan.setLayout(ListKendaraanLayout);
        ListKendaraanLayout.setHorizontalGroup(
            ListKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListKendaraanLayout.createSequentialGroup()
                .addGroup(ListKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListKendaraanLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(ListKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(ListKendaraanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListKendaraanLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ListKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ListKendaraanLayout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        ListKendaraanLayout.setVerticalGroup(
            ListKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListKendaraanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ListKendaraanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DaftarKendaraan.setBackground(new java.awt.Color(255, 255, 255));

        titleFormKendaraan.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titleFormKendaraan.setText("Daftar Kendaraan");

        subTitleFormKendaraan.setText("Harap isi beberapa kolom berikut untuk mendaftakan kendaraan ");

        label1.setText("Nama Kendaraan");

        namaKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKendaraanActionPerformed(evt);
            }
        });

        label2.setText("Merk Kendaraan");

        label3.setText("Warna Kendaraan");

        warnaKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnaKendaraanActionPerformed(evt);
            }
        });

        label8.setText("CC Kendaraan");

        label9.setForeground(new java.awt.Color(204, 204, 204));
        label9.setText("CC");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        label4.setText("Foto Kendaraan");

        img1.setBackground(new java.awt.Color(51, 255, 51));
        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1.setText("+");
        img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img1MousePressed(evt);
            }
        });

        img2.setBackground(new java.awt.Color(51, 255, 51));
        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img2.setText("+");
        img2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img2MousePressed(evt);
            }
        });

        img3.setBackground(new java.awt.Color(51, 255, 51));
        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img3.setText("+");
        img3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img3MousePressed(evt);
            }
        });

        label5.setText("Harga Sewa Kendaraan");

        label6.setForeground(new java.awt.Color(204, 204, 204));
        label6.setText("Rp");

        label7.setText("Kapasitas Kendaraan");

        kapasitas2.setBackground(new java.awt.Color(255, 255, 255));
        kapasitas2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kapasitas2.setForeground(new java.awt.Color(255, 255, 255));
        kapasitas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kapasitas2MousePressed(evt);
            }
        });

        label2org.setText("2 Orang");

        javax.swing.GroupLayout kapasitas2Layout = new javax.swing.GroupLayout(kapasitas2);
        kapasitas2.setLayout(kapasitas2Layout);
        kapasitas2Layout.setHorizontalGroup(
            kapasitas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kapasitas2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(label2org)
                .addGap(27, 27, 27))
        );
        kapasitas2Layout.setVerticalGroup(
            kapasitas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kapasitas2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2org, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        kapasitas4.setBackground(new java.awt.Color(255, 255, 255));
        kapasitas4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kapasitas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kapasitas4MousePressed(evt);
            }
        });

        label4org.setText("4 Orang");

        javax.swing.GroupLayout kapasitas4Layout = new javax.swing.GroupLayout(kapasitas4);
        kapasitas4.setLayout(kapasitas4Layout);
        kapasitas4Layout.setHorizontalGroup(
            kapasitas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kapasitas4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label4org)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        kapasitas4Layout.setVerticalGroup(
            kapasitas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kapasitas4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4org, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        kapasitas6.setBackground(new java.awt.Color(255, 255, 255));
        kapasitas6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kapasitas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kapasitas6MousePressed(evt);
            }
        });

        label6org.setText("6 Orang");

        javax.swing.GroupLayout kapasitas6Layout = new javax.swing.GroupLayout(kapasitas6);
        kapasitas6.setLayout(kapasitas6Layout);
        kapasitas6Layout.setHorizontalGroup(
            kapasitas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kapasitas6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(label6org)
                .addGap(27, 27, 27))
        );
        kapasitas6Layout.setVerticalGroup(
            kapasitas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kapasitas6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6org, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        save.setBackground(new java.awt.Color(0, 61, 127));
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.setForeground(new java.awt.Color(0, 61, 127));

        textBtnFormKendaraan.setForeground(new java.awt.Color(255, 255, 255));
        textBtnFormKendaraan.setText("Selanjutnya");

        iconArrowFormKendaraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Arrow.png"))); // NOI18N

        javax.swing.GroupLayout saveLayout = new javax.swing.GroupLayout(save);
        save.setLayout(saveLayout);
        saveLayout.setHorizontalGroup(
            saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(textBtnFormKendaraan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconArrowFormKendaraan)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        saveLayout.setVerticalGroup(
            saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(saveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textBtnFormKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconArrowFormKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout DaftarKendaraanLayout = new javax.swing.GroupLayout(DaftarKendaraan);
        DaftarKendaraan.setLayout(DaftarKendaraanLayout);
        DaftarKendaraanLayout.setHorizontalGroup(
            DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarKendaraanLayout.createSequentialGroup()
                .addContainerGap(1348, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleFormKendaraan)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTitleFormKendaraan)
                    .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                        .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                        .addComponent(ccKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(warnaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(merkKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87))
                            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idKendaraan)
                                .addGap(39, 39, 39)))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(hargaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                .addComponent(kapasitas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kapasitas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kapasitas6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(702, Short.MAX_VALUE))
        );
        DaftarKendaraanLayout.setVerticalGroup(
            DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleFormKendaraan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTitleFormKendaraan)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                        .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(idKendaraan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(merkKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(warnaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(DaftarKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DaftarKendaraanLayout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kapasitas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kapasitas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kapasitas6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DaftarKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(324, 324, 324)
                    .addComponent(ListKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 767, Short.MAX_VALUE)
                    .addComponent(DaftarKendaraanSukses, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DaftarKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DaftarKendaraanSukses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarKendaraanMouseEntered(java.awt.event.MouseEvent evt) {
        setColor(daftarKendaraan);
    }

    private void daftarKendaraanMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        resetColor(daftarKendaraan);
    }

    private void updateKendaraanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateKendaraanMouseEntered
        setColor(updateKendaraan);
    }//GEN-LAST:event_updateKendaraanMouseEntered

    private void updateKendaraanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateKendaraanMouseExited
        resetColor(updateKendaraan);
    }//GEN-LAST:event_updateKendaraanMouseExited

    private void setClicked(JPanel p1, JPanel p2, JLabel l1, JLabel l2) {
        p1.setBackground(new Color(0, 43, 110));
        l1.setForeground(new Color(255, 216, 82));
        p2.setBackground(new Color(0, 63, 130));
        l2.setForeground(new Color(255, 255, 255));
    }

    private void listMerk() {
        String[] merk = {"Honda", "Suzuki", "BMW", "Mercedes Benz", "Toyota"};
        Arrays.sort(merk);
        for (String v : merk) {
            merkKendaraan.add(v);
        }
    }

    private void listCC() {
        String[] cc = {"200", "300", "1000"};
        Arrays.sort(cc);
        for (String v : cc) {
            ccKendaraan.add(v);
        }
    }

    private void setColor(JPanel p) {
        p.setBackground(new Color(0, 53, 130));
    }

    private void resetColor(JPanel p) {
        p.setBackground(new Color(0, 63, 130));
    }


    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMousePressed

    private void namaKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKendaraanActionPerformed

    private void warnaKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnaKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warnaKendaraanActionPerformed

    private void kapasitas2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapasitas2MousePressed
        kapasitas4.setBackground(Color.white);
        kapasitas6.setBackground(Color.white);
        kapasitas2.setBackground(Color.decode("#003F82"));
        label2org.setForeground(Color.white);
        label4org.setForeground(Color.black);
        label6org.setForeground(Color.black);
        kapasitas = "2";
    }//GEN-LAST:event_kapasitas2MousePressed

    public JLabel getIdKendaraan() {
        return idKendaraan;
    }

    public void setIdKendaraan(JLabel idKendaraan) {
        this.idKendaraan = idKendaraan;
    }

    public JLabel getLabel2org() {
        return label2org;
    }

    public JLabel getLabel4org() {
        return label4org;
    }

    public JLabel getLabel6org() {
        return label6org;
    }

    public JPanel getKapasitas2() {
        return kapasitas2;
    }

    public JPanel getKapasitas4() {
        return kapasitas4;
    }

    public JPanel getKapasitas6() {
        return kapasitas6;
    }

    private void kapasitas4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapasitas4MousePressed
        kapasitas4.setBackground(Color.decode("#003F82"));
        kapasitas6.setBackground(Color.white);
        kapasitas2.setBackground(Color.white);
        label4org.setForeground(Color.white);
        label2org.setForeground(Color.black);
        label6org.setForeground(Color.black);
        kapasitas = "4";
    }//GEN-LAST:event_kapasitas4MousePressed

    private void kapasitas6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapasitas6MousePressed
        kapasitas4.setBackground(Color.white);
        kapasitas6.setBackground(Color.decode("#003F82"));
        kapasitas2.setBackground(Color.white);
        label6org.setForeground(Color.white);
        label4org.setForeground(Color.black);
        label2org.setForeground(Color.black);
        kapasitas = "6";
    }//GEN-LAST:event_kapasitas6MousePressed

    private void daftarKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarKendaraanMouseClicked
        DaftarKendaraan.setVisible(true);
        ListKendaraan.setVisible(false);
        setClicked(daftarKendaraan, updateKendaraan, jLabel10, riwataRentalTxt);
    }//GEN-LAST:event_daftarKendaraanMouseClicked

    private void riwataRentalTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwataRentalTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_riwataRentalTxtMouseClicked

    private void updateKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateKendaraanMouseClicked
        ListKendaraan.setVisible(true);
        DaftarKendaraan.setVisible(false);
        setClicked(updateKendaraan, daftarKendaraan, riwataRentalTxt, jLabel10);
    }//GEN-LAST:event_updateKendaraanMouseClicked

    private void img1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img1MousePressed
        int returnValue = openFile.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            image1 = openFile.getSelectedFile();
            try {
                originalBI1 = ImageIO.read(image1);
            } catch (IOException ex) {
                Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
            }

            Image dimg = originalBI1.getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(dimg);
            img1.setText(null);
            img1.setIcon(image);
        }
    }//GEN-LAST:event_img1MousePressed

    private void img2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MousePressed
        int returnValue = openFile.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            image2 = openFile.getSelectedFile();
            try {
                originalBI1 = ImageIO.read(image2);
            } catch (IOException ex) {
                Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
            }

            Image dimg = originalBI1.getScaledInstance(img2.getWidth(), img2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(dimg);
            img2.setText(null);
            img2.setIcon(image);
        }
    }//GEN-LAST:event_img2MousePressed

    private void img3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img3MousePressed
        int returnValue = openFile.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            image3 = openFile.getSelectedFile();
            try {
                originalBI1 = ImageIO.read(image3);
            } catch (IOException ex) {
                Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
            }

            Image dimg = originalBI1.getScaledInstance(img3.getWidth(), img3.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(dimg);
            img3.setText(null);
            img3.setIcon(image);
    }//GEN-LAST:event_img3MousePressed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    public JLabel getSubText1() {
        return subText1;
    }

    public void setSubText1(JLabel subText1) {
        this.subText1 = subText1;
    }

    public JLabel getSubText2() {
        return subText2;
    }

    public void setSubText2(JLabel subText2) {
        this.subText2 = subText2;
    }

    public JLabel getSubTextDaftarSukses() {
        return subTextDaftarSukses;
    }

    public void setSubTextDaftarSukses(JLabel subTextDaftarSukses) {
        this.subTextDaftarSukses = subTextDaftarSukses;
    }

    public JLabel getSubTitleDaftarSukses() {
        return subTitleDaftarSukses;
    }

    public void setSubTitleDaftarSukses(JLabel subTitleDaftarSukses) {
        this.subTitleDaftarSukses = subTitleDaftarSukses;
    }

    public JLabel getTextDaftarSukses() {
        return textDaftarSukses;
    }

    public void setTextDaftarSukses(JLabel textDaftarSukses) {
        this.textDaftarSukses = textDaftarSukses;
    }

    public JLabel getTitleDaftarSukses() {
        return titleDaftarSukses;
    }

    public void setTitleDaftarSukses(JLabel titleDaftarSukses) {
        this.titleDaftarSukses = titleDaftarSukses;
    }

    public String getKapasitas() {
        return kapasitas;
    }

    public void setKapasitas(String kapasitas) {
        this.kapasitas = kapasitas;
    }

    public File getImage1() {
        return image1;
    }

    public void setImage1(File image1) {
        this.image1 = image1;
    }

    public File getImage2() {
        return image2;
    }

    public void setImage2(File image2) {
        this.image2 = image2;
    }

    public File getImage3() {
        return image3;
    }

    public void setImage3(File image3) {
        this.image3 = image3;
    }

    public JPanel getDaftarKendaraan() {
        return DaftarKendaraan;
    }

    public void setDaftarKendaraan(JPanel DaftarKendaraan) {
        this.DaftarKendaraan = DaftarKendaraan;
    }

    public JPanel getListKendaraan() {
        return ListKendaraan;
    }

    public void setListKendaraan(JPanel ListKendaraan) {
        this.ListKendaraan = ListKendaraan;
    }

    public JPanel getTabMenu() {
        return TabMenu;
    }

    public void setTabMenu(JPanel TabMenu) {
        this.TabMenu = TabMenu;
    }

    public Choice getCcKendaraan() {
        return ccKendaraan;
    }

    public void setCcKendaraan(Choice ccKendaraan) {
        this.ccKendaraan = ccKendaraan;
    }

    public JLabel getEmail() {
        return email;
    }

    public void setEmail(JLabel email) {
        this.email = email;
    }

    public TextField getHargaKendaraan() {
        return hargaKendaraan;
    }

    public JPanel getDaftarKendaraanSukses() {
        return DaftarKendaraanSukses;
    }

    public void setHargaKendaraan(TextField hargaKendaraan) {
        this.hargaKendaraan = hargaKendaraan;
    }

    public JPanel getListPanel() {
        return listPanel;
    }

    public void setListPanel(JPanel listPanel) {
        this.listPanel = listPanel;
    }

    public Choice getMerkKendaraan() {
        return merkKendaraan;
    }

    public void setMerkKendaraan(Choice merkKendaraan) {
        this.merkKendaraan = merkKendaraan;
    }

    public TextField getNamaKendaraan() {
        return namaKendaraan;
    }

    public void setNamaKendaraan(TextField namaKendaraan) {
        this.namaKendaraan = namaKendaraan;
    }

    public JLabel getPp() {
        return pp;
    }

    public void setPp(JLabel pp) {
        this.pp = pp;
    }

    public JPanel getSearch() {
        return search;
    }

    public void setSearch(JPanel search) {
        this.search = search;
    }

    public JTextField getSearchField() {
        return searchField;
    }

    public void setSearchField(JTextField searchField) {
        this.searchField = searchField;
    }

    public JPanel getUpdateKendaraan() {
        return updateKendaraan;
    }

    public void setUpdateKendaraan(JPanel updateKendaraan) {
        this.updateKendaraan = updateKendaraan;
    }

    public JLabel getUsername() {
        return username;
    }

    public void setUsername(JLabel username) {
        this.username = username;
    }

    public TextField getWarnaKendaraan() {
        return warnaKendaraan;
    }

    public void setWarnaKendaraan(TextField warnaKendaraan) {
        this.warnaKendaraan = warnaKendaraan;
    }

    @Override
    public void addMouseListener(MouseListener me) {
        save.addMouseListener(me);
        search.addMouseListener(me);
        nextDaftarBtn.addMouseListener(me);
        exitBtn.addMouseListener(me);
        updateKendaraan.addMouseListener(me);
    }

    public JPanel getNextDaftarBtn() {
        return nextDaftarBtn;
    }

    public JLabel getSubTitleFormKendaraan() {
        return subTitleFormKendaraan;
    }

    public JLabel getTitleFormKendaraan() {
        return titleFormKendaraan;
    }

    public JLabel getIconArrowFormKendaraan() {
        return iconArrowFormKendaraan;
    }

    public JLabel getTextBtnFormKendaraan() {
        return textBtnFormKendaraan;
    }

    public JLabel getImg1() {
        return img1;
    }

    public JLabel getImg2() {
        return img2;
    }

    public JLabel getImg3() {
        return img3;
    }

    public JPanel getExitBtn() {
        return exitBtn;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DaftarKendaraan;
    private javax.swing.JPanel DaftarKendaraanSukses;
    private javax.swing.JPanel ListKendaraan;
    private javax.swing.JPanel TabMenu;
    private java.awt.Choice ccKendaraan;
    private javax.swing.JPanel daftarKendaraan;
    private javax.swing.JLabel email;
    private javax.swing.JPanel exitBtn;
    private java.awt.TextField hargaKendaraan;
    private javax.swing.JLabel iconArrowFormKendaraan;
    private javax.swing.JLabel idKendaraan;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelItem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel kapasitas2;
    private javax.swing.JPanel kapasitas4;
    private javax.swing.JPanel kapasitas6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel label2org;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel label4org;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JLabel label6org;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JPanel listPanel;
    private java.awt.Choice merkKendaraan;
    private java.awt.TextField namaKendaraan;
    private javax.swing.JPanel nextDaftarBtn;
    private javax.swing.JLabel pp;
    private javax.swing.JLabel riwataRentalTxt;
    private javax.swing.JPanel save;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel subText1;
    private javax.swing.JLabel subText2;
    private javax.swing.JLabel subTextDaftarSukses;
    private javax.swing.JLabel subTitleDaftarSukses;
    private javax.swing.JLabel subTitleFormKendaraan;
    private javax.swing.JLabel textBtnFormKendaraan;
    private javax.swing.JLabel textDaftarSukses;
    private javax.swing.JLabel titleDaftarSukses;
    private javax.swing.JLabel titleFormKendaraan;
    private javax.swing.JPanel updateKendaraan;
    private javax.swing.JLabel username;
    private java.awt.TextField warnaKendaraan;
    // End of variables declaration//GEN-END:variables
}
