/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author AsusPRO
 */
public class DetailKendaraan extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtamaListKendaraan
     */
    public DetailKendaraan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        katalogKendaraan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        riwayatRental = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaKendaraan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        merkKendaraan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        warnaKendaraan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ccKendaraan = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        gambar1 = new javax.swing.JLabel();
        gambar2 = new javax.swing.JLabel();
        gambar3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        kapasitasKendaraan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        branchKatalog = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 63, 130));

        katalogKendaraan.setBackground(new java.awt.Color(0, 43, 130));
        katalogKendaraan.setPreferredSize(new java.awt.Dimension(323, 64));

        jLabel1.setFont(new java.awt.Font("Mulish", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 216, 82));
        jLabel1.setText("Katalog Kendaraan");

        javax.swing.GroupLayout katalogKendaraanLayout = new javax.swing.GroupLayout(katalogKendaraan);
        katalogKendaraan.setLayout(katalogKendaraanLayout);
        katalogKendaraanLayout.setHorizontalGroup(
            katalogKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(katalogKendaraanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        katalogKendaraanLayout.setVerticalGroup(
            katalogKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, katalogKendaraanLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        riwayatRental.setBackground(new java.awt.Color(0, 63, 130));
        riwayatRental.setPreferredSize(new java.awt.Dimension(323, 64));
        riwayatRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatRentalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatRentalMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Mulish", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Riwayat Rental");

        javax.swing.GroupLayout riwayatRentalLayout = new javax.swing.GroupLayout(riwayatRental);
        riwayatRental.setLayout(riwayatRentalLayout);
        riwayatRentalLayout.setHorizontalGroup(
            riwayatRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatRentalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        riwayatRentalLayout.setVerticalGroup(
            riwayatRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatRentalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(239, 56));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Mulish", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(165, 0, 0));
        jLabel7.setText("Keluar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(67, 67, 67))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Line 29.png"))); // NOI18N

        username.setFont(new java.awt.Font("Mulish", 1, 22)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Optimum Pride");

        email.setFont(new java.awt.Font("Mulish Medium", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(102, 140, 180));
        email.setText("emaeil@email.com");

        pp.setText("jLabel11");
        pp.setPreferredSize(new java.awt.Dimension(56, 56));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(katalogKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(riwayatRental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username)
                            .addComponent(email)))
                    .addComponent(jLabel8)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(81, 81, 81)
                .addComponent(katalogKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(riwayatRental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email))
                    .addComponent(pp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(877, 675));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/detail_kendaraan.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(139, 139, 139));
        jLabel4.setText("Nama Kendaraan");

        namaKendaraan.setFont(new java.awt.Font("Mulish", 1, 30)); // NOI18N
        namaKendaraan.setForeground(new java.awt.Color(49, 49, 49));
        namaKendaraan.setText("Alphard Tipe X");

        jLabel10.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(139, 139, 139));
        jLabel10.setText("Merk Kendaraan");

        merkKendaraan.setFont(new java.awt.Font("Mulish", 1, 30)); // NOI18N
        merkKendaraan.setForeground(new java.awt.Color(49, 49, 49));
        merkKendaraan.setText("Toyota");

        jLabel12.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(139, 139, 139));
        jLabel12.setText("Warna Kendaraan");

        warnaKendaraan.setFont(new java.awt.Font("Mulish", 1, 30)); // NOI18N
        warnaKendaraan.setForeground(new java.awt.Color(49, 49, 49));
        warnaKendaraan.setText("Hitam");

        jLabel14.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(139, 139, 139));
        jLabel14.setText("CC Kendaraan");

        ccKendaraan.setFont(new java.awt.Font("Mulish", 1, 30)); // NOI18N
        ccKendaraan.setForeground(new java.awt.Color(49, 49, 49));
        ccKendaraan.setText("250");

        jLabel16.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(139, 139, 139));
        jLabel16.setText("CC");

        jSeparator1.setBackground(new java.awt.Color(139, 139, 139));
        jSeparator1.setForeground(new java.awt.Color(139, 139, 139));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel17.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(139, 139, 139));
        jLabel17.setText("Foto Kendaraan");

        gambar1.setText("Gambar 1");
        gambar1.setPreferredSize(new java.awt.Dimension(96, 96));

        gambar2.setText("Gambar 2");
        gambar2.setPreferredSize(new java.awt.Dimension(96, 96));

        gambar3.setText("Gambar 3");
        gambar3.setPreferredSize(new java.awt.Dimension(96, 96));

        jLabel21.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(139, 139, 139));
        jLabel21.setText("Harga Sewa Kendaraan");

        jLabel22.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(139, 139, 139));
        jLabel22.setText("Rp");

        harga.setFont(new java.awt.Font("Mulish", 1, 30)); // NOI18N
        harga.setForeground(new java.awt.Color(49, 49, 49));
        harga.setText("800.000,00");

        jLabel24.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(139, 139, 139));
        jLabel24.setText("Per Hari");

        jLabel25.setFont(new java.awt.Font("Mulish Medium", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(139, 139, 139));
        jLabel25.setText("Kapasitas Kendaraan");

        kapasitasKendaraan.setFont(new java.awt.Font("Mulish", 1, 30)); // NOI18N
        kapasitasKendaraan.setForeground(new java.awt.Color(49, 49, 49));
        kapasitasKendaraan.setText("4");

        jPanel4.setBackground(new java.awt.Color(0, 63, 130));
        jPanel4.setPreferredSize(new java.awt.Dimension(276, 72));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Arrow.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Mulish", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Rental Kendaraan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(27, 27, 27)
                .addComponent(jLabel27)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addGap(23, 23, 23))
        );

        jLabel31.setFont(new java.awt.Font("Mulish", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(65, 65, 65));
        jLabel31.setText("Detail Kendaraan");

        branchKatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/katalog (2).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Mulish", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 49, 49));
        jLabel9.setText("Orang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ccKendaraan)
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel16))
                                    .addComponent(jLabel14)
                                    .addComponent(warnaKendaraan)
                                    .addComponent(jLabel12)
                                    .addComponent(merkKendaraan)
                                    .addComponent(jLabel10)
                                    .addComponent(namaKendaraan)
                                    .addComponent(jLabel4))
                                .addGap(122, 122, 122)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(gambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(gambar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(gambar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(16, 16, 16)
                                        .addComponent(harga)
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel24))
                                    .addComponent(jLabel25)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(kapasitasKendaraan)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel9))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(branchKatalog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)))
                        .addGap(6, 6, 6)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(branchKatalog, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(namaKendaraan)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addComponent(merkKendaraan)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(warnaKendaraan)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccKendaraan)
                            .addComponent(jLabel16)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gambar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gambar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel21)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(harga)
                            .addComponent(jLabel24))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel25)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kapasitasKendaraan)
                            .addComponent(jLabel9))))
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatRentalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatRentalMouseEntered
        setColor(riwayatRental);
    }//GEN-LAST:event_riwayatRentalMouseEntered

    private void riwayatRentalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatRentalMouseExited
        resetColor(riwayatRental);
    }//GEN-LAST:event_riwayatRentalMouseExited

    private void setColor(JPanel p) {
        p.setBackground(new Color(0, 53, 130));
    }

    private void resetColor(JPanel p) {
        p.setBackground(new Color(0, 63, 130));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailKendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel branchKatalog;
    private javax.swing.JLabel ccKendaraan;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gambar1;
    private javax.swing.JLabel gambar2;
    private javax.swing.JLabel gambar3;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kapasitasKendaraan;
    private javax.swing.JPanel katalogKendaraan;
    private javax.swing.JLabel merkKendaraan;
    private javax.swing.JLabel namaKendaraan;
    private javax.swing.JLabel pp;
    private javax.swing.JPanel riwayatRental;
    private javax.swing.JLabel username;
    private javax.swing.JLabel warnaKendaraan;
    // End of variables declaration//GEN-END:variables

    public JLabel getBranchKatalog() {
        return branchKatalog;
    }

    public void addMouseListener(MouseListener me) {
        branchKatalog.addMouseListener(me);
    }

    public JLabel getCcKendaraan() {
        return ccKendaraan;
    }

    public JLabel getGambar1() {
        return gambar1;
    }

    public JLabel getGambar2() {
        return gambar2;
    }

    public JLabel getGambar3() {
        return gambar3;
    }

    public JLabel getHarga() {
        return harga;
    }

    public JLabel getKapasitasKendaraan() {
        return kapasitasKendaraan;
    }

    public JLabel getMerkKendaraan() {
        return merkKendaraan;
    }

    public JLabel getNamaKendaraan() {
        return namaKendaraan;
    }

    public JLabel getWarnaKendaraan() {
        return warnaKendaraan;
    }

}
