/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DaftarKendaraanController;
import java.awt.Choice;
import java.awt.Color;
import java.awt.Image;
import java.awt.TextField;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AsusPRO
 */
public class MenuUtamaDaftarKendaraan extends javax.swing.JFrame {

    private final JFileChooser openFile;

    public BufferedImage getOriginalBI1() {
        return originalBI1;
    }

    private BufferedImage originalBI1;
    private BufferedImage originalBI2;
    private BufferedImage originalBI3;
    private File image1;
    private File image2;
    private File image3;

    public File getImage1() {
        return image1;
    }

    public File getImage2() {
        return image2;
    }

    public File getImage3() {
        return image3;
    }

    private String kapasitas;

    /**
     * Creates new form MenuUtama
     */
    public MenuUtamaDaftarKendaraan() {
        initComponents();
        listMerk();
        listCC();
        openFile = new JFileChooser();
        openFile.setFileFilter(new FileNameExtensionFilter("Image", "jpeg", "png", "jpg"));
    }

    private void listMerk() {
        String[] merk = { "Honda", "Suzuki", "BMW", "Mercedes Benz", "Toyota" };
        Arrays.sort(merk);
        for (String v : merk) {
            merkKendaraan.add(v);
        }
    }

    private void listCC() {
        String[] cc = { "200", "300", "1000" };
        Arrays.sort(cc);
        for (String v : cc) {
            ccKendaraan.add(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        warnaKendaraan = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        merkKendaraan = new java.awt.Choice();
        label3 = new java.awt.Label();
        namaKendaraan = new java.awt.TextField();
        label4 = new java.awt.Label();
        panelImg1 = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        hargaKendaraan = new java.awt.TextField();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        kapasitas2 = new javax.swing.JPanel();
        label2org = new javax.swing.JLabel();
        kapasitas6 = new javax.swing.JPanel();
        label6org = new javax.swing.JLabel();
        kapasitas4 = new javax.swing.JPanel();
        label4org = new javax.swing.JLabel();
        ccKendaraan = new java.awt.Choice();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        save = new javax.swing.JButton();
        panelImg2 = new javax.swing.JPanel();
        img2 = new javax.swing.JLabel();
        panelImg3 = new javax.swing.JPanel();
        img3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 675));

        jPanel1.setBackground(new java.awt.Color(0, 61, 127));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 332, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 681, Short.MAX_VALUE));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 675));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Daftar Kendaraan");

        jLabel2.setText("Harap isi beberapa kolom berikut untuk mendaftakan kendaraan ");

        warnaKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnaKendaraanActionPerformed(evt);
            }
        });

        label1.setText("Nama Kendaraan");

        label2.setText("Merk Kendaraan");

        label3.setText("Warna Kendaraan");

        namaKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKendaraanActionPerformed(evt);
            }
        });

        label4.setText("Foto Kendaraan");

        panelImg1.setBackground(new java.awt.Color(255, 255, 255));
        panelImg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImg1.setPreferredSize(new java.awt.Dimension(85, 85));
        panelImg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelImg1MousePressed(evt);
            }
        });

        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1.setText("+");

        javax.swing.GroupLayout panelImg1Layout = new javax.swing.GroupLayout(panelImg1);
        panelImg1.setLayout(panelImg1Layout);
        panelImg1Layout.setHorizontalGroup(
                panelImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE));
        panelImg1Layout.setVerticalGroup(
                panelImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE));

        label5.setText("Harga Sewa Kendaraan");

        label6.setForeground(new java.awt.Color(204, 204, 204));
        label6.setText("Rp");

        label7.setText("Kapasitas Kendaraan");

        kapasitas2.setBackground(new java.awt.Color(255, 255, 255));
        kapasitas2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kapasitas2.setForeground(new java.awt.Color(255, 255, 255));
        kapasitas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kapasitas2MousePressed(evt);
            }
        });

        label2org.setText("2 Orang");

        javax.swing.GroupLayout kapasitas2Layout = new javax.swing.GroupLayout(kapasitas2);
        kapasitas2.setLayout(kapasitas2Layout);
        kapasitas2Layout.setHorizontalGroup(
                kapasitas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kapasitas2Layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addComponent(label2org)
                                .addGap(27, 27, 27)));
        kapasitas2Layout.setVerticalGroup(
                kapasitas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kapasitas2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label2org, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addContainerGap()));

        kapasitas6.setBackground(new java.awt.Color(255, 255, 255));
        kapasitas6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kapasitas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kapasitas6MousePressed(evt);
            }
        });

        label6org.setText("6 Orang");

        javax.swing.GroupLayout kapasitas6Layout = new javax.swing.GroupLayout(kapasitas6);
        kapasitas6.setLayout(kapasitas6Layout);
        kapasitas6Layout.setHorizontalGroup(
                kapasitas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kapasitas6Layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addComponent(label6org)
                                .addGap(27, 27, 27)));
        kapasitas6Layout.setVerticalGroup(
                kapasitas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kapasitas6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label6org, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addContainerGap()));

        kapasitas4.setBackground(new java.awt.Color(255, 255, 255));
        kapasitas4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kapasitas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kapasitas4MousePressed(evt);
            }
        });

        label4org.setText("4 Orang");

        javax.swing.GroupLayout kapasitas4Layout = new javax.swing.GroupLayout(kapasitas4);
        kapasitas4.setLayout(kapasitas4Layout);
        kapasitas4Layout.setHorizontalGroup(
                kapasitas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kapasitas4Layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addComponent(label4org)
                                .addGap(27, 27, 27)));
        kapasitas4Layout.setVerticalGroup(
                kapasitas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kapasitas4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label4org, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addContainerGap()));

        label8.setText("CC Kendaraan");

        label9.setForeground(new java.awt.Color(204, 204, 204));
        label9.setText("CC");

        save.setText("Selanjutnya");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        panelImg2.setBackground(new java.awt.Color(255, 255, 255));
        panelImg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImg2.setPreferredSize(new java.awt.Dimension(85, 85));

        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img2.setText("+");
        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelImg2Layout = new javax.swing.GroupLayout(panelImg2);
        panelImg2.setLayout(panelImg2Layout);
        panelImg2Layout.setHorizontalGroup(
                panelImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE));
        panelImg2Layout.setVerticalGroup(
                panelImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE));

        panelImg3.setBackground(new java.awt.Color(255, 255, 255));
        panelImg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImg3.setPreferredSize(new java.awt.Dimension(85, 85));
        panelImg3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelImg3MousePressed(evt);
            }
        });

        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img3.setText("+");

        javax.swing.GroupLayout panelImg3Layout = new javax.swing.GroupLayout(panelImg3);
        panelImg3.setLayout(panelImg3Layout);
        panelImg3Layout.setHorizontalGroup(
                panelImg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE));
        panelImg3Layout.setVerticalGroup(
                panelImg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(warnaKendaraan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 208,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(namaKendaraan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 208,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(merkKendaraan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 208,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(ccKendaraan,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 208,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(label9,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        379, Short.MAX_VALUE)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(111, 111, 111)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(panelImg1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(panelImg2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(panelImg3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(label6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(hargaKendaraan,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 288,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(kapasitas2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(kapasitas4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(kapasitas6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(90, 90, 90))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 222,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(panelImg1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(panelImg2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(panelImg3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(label3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(warnaKendaraan,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(label8,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(ccKendaraan,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(label9,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(label5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(hargaKendaraan,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(label6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(label7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(kapasitas2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(kapasitas4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(kapasitas6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(namaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(merkKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 277,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveActionPerformed
    }// GEN-LAST:event_saveActionPerformed

    private void kapasitas4MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kapasitas4MousePressed
        kapasitas4.setBackground(Color.GRAY);
        kapasitas6.setBackground(Color.white);
        kapasitas2.setBackground(Color.white);
        label4org.setForeground(Color.white);
        label2org.setForeground(Color.black);
        label6org.setForeground(Color.black);
        kapasitas = "4";
    }// GEN-LAST:event_kapasitas4MousePressed

    private void kapasitas6MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kapasitas6MousePressed
        kapasitas4.setBackground(Color.white);
        kapasitas6.setBackground(Color.GRAY);
        kapasitas2.setBackground(Color.white);
        label6org.setForeground(Color.white);
        label4org.setForeground(Color.black);
        label2org.setForeground(Color.black);
        kapasitas = "6";
    }// GEN-LAST:event_kapasitas6MousePressed

    private void kapasitas2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kapasitas2MousePressed
        kapasitas4.setBackground(Color.white);
        kapasitas6.setBackground(Color.white);
        kapasitas2.setBackground(Color.GRAY);
        label2org.setForeground(Color.white);
        label4org.setForeground(Color.black);
        label6org.setForeground(Color.black);
        kapasitas = "2";
    }// GEN-LAST:event_kapasitas2MousePressed

    public String getKapasitas() {
        return kapasitas;
    }

    private void namaKendaraanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_namaKendaraanActionPerformed
    }// GEN-LAST:event_namaKendaraanActionPerformed

    private void warnaKendaraanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_warnaKendaraanActionPerformed
    }// GEN-LAST:event_warnaKendaraanActionPerformed

    private void panelImg1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_panelImg1MousePressed
        int returnValue = openFile.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                image1 = openFile.getSelectedFile();
                originalBI1 = ImageIO.read(image1);
            } catch (IOException ioe) {

            }

            Image dimg = originalBI1.getScaledInstance(img1.getWidth(), img1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(dimg);

            img1.setIcon(image);
            panelImg1.add(img1);
        }
    }// GEN-LAST:event_panelImg1MousePressed

    private void img2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_img2MousePressed
        int returnValue = openFile.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                image2 = openFile.getSelectedFile();
                originalBI2 = ImageIO.read(image2);
            } catch (IOException ioe) {

            }

            Image dimg = originalBI2.getScaledInstance(img2.getWidth(), img2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(dimg);

            img2.setIcon(image);
            panelImg2.add(img2);
        }
    }// GEN-LAST:event_img2MousePressed

    private void panelImg3MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_panelImg3MousePressed
        int returnValue = openFile.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                image3 = openFile.getSelectedFile();
                originalBI3 = ImageIO.read(image3);
            } catch (IOException ioe) {
            }

            Image dimg = originalBI3.getScaledInstance(img3.getWidth(), img3.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(dimg);

            img3.setIcon(image);
            panelImg3.add(img3);
        }
    }// GEN-LAST:event_panelImg3MousePressed

    public BufferedImage getOriginalBI2() {
        return originalBI2;
    }

    public BufferedImage getOriginalBI3() {
        return originalBI3;
    }

    public Choice getCcKendaraan() {
        return ccKendaraan;
    }

    public TextField getHargaKendaraan() {
        return hargaKendaraan;
    }

    public JLabel getImg1() {
        return img1;
    }

    public JLabel getImg2() {
        return img2;
    }

    public JLabel getImg3() {
        return img3;
    }

    public JPanel getKapasitas2() {
        return kapasitas2;
    }

    public JPanel getKapasitas4() {
        return kapasitas4;
    }

    public JPanel getKapasitas6() {
        return kapasitas6;
    }

    public Choice getMerkKendaraan() {
        return merkKendaraan;
    }

    public TextField getNamaKendaraan() {
        return namaKendaraan;
    }

    public JPanel getPanelImg1() {
        return panelImg1;
    }

    public JPanel getPanelImg2() {
        return panelImg2;
    }

    public JPanel getPanelImg3() {
        return panelImg3;
    }

    public JButton getSave() {
        return save;
    }

    public TextField getWarnaKendaraan() {
        return warnaKendaraan;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDaftarKendaraan.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDaftarKendaraan.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDaftarKendaraan.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDaftarKendaraan.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaDaftarKendaraan().setVisible(true);
            }
        });
    }

    private java.awt.Choice ccKendaraan;
    private java.awt.TextField hargaKendaraan;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel kapasitas2;
    private javax.swing.JPanel kapasitas4;
    private javax.swing.JPanel kapasitas6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel label2org;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel label4org;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JLabel label6org;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Choice merkKendaraan;
    private java.awt.TextField namaKendaraan;
    private javax.swing.JPanel panelImg1;
    private javax.swing.JPanel panelImg2;
    private javax.swing.JPanel panelImg3;
    private javax.swing.JButton save;
    private java.awt.TextField warnaKendaraan;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(DaftarKendaraanController aThis) {
        save.addActionListener(aThis);
    }
}
