/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author AsusPRO
 */
public class Registrasi2 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Registrasi2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Subheading = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        daftarBtn = new javax.swing.JButton();
        FotoKTP = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Statuspage = new javax.swing.JLabel();
        Totalpage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        unggahKTPBtn = new javax.swing.JButton();
        pathKTP = new javax.swing.JTextField();
        pathFoto = new javax.swing.JTextField();
        unggahFotoBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Frame 57 (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 540));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Heading.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Heading.setText("Registrasi");

        Subheading.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Subheading.setForeground(new java.awt.Color(51, 51, 51));
        Subheading.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Subheading.setText("Daftar akun untuk memulai fitur menarik");

        Alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Alamat.setForeground(new java.awt.Color(51, 51, 51));
        Alamat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alamat.setText("Alamat");

        daftarBtn.setBackground(new java.awt.Color(51, 51, 255));
        daftarBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        daftarBtn.setForeground(new java.awt.Color(255, 255, 255));
        daftarBtn.setText("Daftar");
        daftarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        daftarBtn.setFocusable(false);
        daftarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBtnActionPerformed(evt);
            }
        });

        FotoKTP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FotoKTP.setForeground(new java.awt.Color(51, 51, 51));
        FotoKTP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FotoKTP.setText("Foto KTP");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Foto Diri");

        Statuspage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Statuspage.setText("2");

        Totalpage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Totalpage.setForeground(new java.awt.Color(102, 102, 102));
        Totalpage.setText("dari 2");

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alamat.setRows(5);
        alamat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(alamat);

        unggahKTPBtn.setBackground(new java.awt.Color(255, 102, 0));
        unggahKTPBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unggahKTPBtn.setForeground(new java.awt.Color(255, 255, 255));
        unggahKTPBtn.setText("Unggah Foto");
        unggahKTPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unggahKTPBtnActionPerformed(evt);
            }
        });

        pathKTP.setText("Unggah foto KTP");
        pathKTP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pathKTP.setEnabled(false);

        pathFoto.setText("Unggah foto diri");
        pathFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pathFoto.setEnabled(false);

        unggahFotoBtn.setBackground(new java.awt.Color(255, 102, 0));
        unggahFotoBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unggahFotoBtn.setForeground(new java.awt.Color(255, 255, 255));
        unggahFotoBtn.setText("Unggah Foto");

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/chevron-left 1 (2).png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Statuspage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Totalpage))
                    .addComponent(Heading, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Subheading, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alamat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daftarBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(FotoKTP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pathKTP)
                            .addComponent(pathFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unggahFotoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unggahKTPBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Statuspage)
                        .addComponent(Totalpage))
                    .addComponent(backBtn))
                .addGap(13, 13, 13)
                .addComponent(Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Subheading)
                .addGap(36, 36, 36)
                .addComponent(Alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FotoKTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unggahKTPBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(pathKTP))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unggahFotoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(daftarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daftarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void unggahKTPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unggahKTPBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unggahKTPBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel FotoKTP;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Statuspage;
    private javax.swing.JLabel Subheading;
    private javax.swing.JLabel Totalpage;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton daftarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pathFoto;
    private javax.swing.JTextField pathKTP;
    private javax.swing.JButton unggahFotoBtn;
    private javax.swing.JButton unggahKTPBtn;
    // End of variables declaration//GEN-END:variables

    public JTextArea getAlamat() {
        return alamat;
    }

    public JButton getBackBtn() {
        return backBtn;
    }

    public JButton getDaftarBtn() {
        return daftarBtn;
    }

    public JButton getUnggahFotoBtn() {
        return unggahFotoBtn;
    }

    public JButton getUnggahKTPBtn() {
        return unggahKTPBtn;
    }

    public JTextField getPathFoto() {
        return pathFoto;
    }

    public JTextField getPathKTP() {
        return pathKTP;
    }

    public void addActionListener(ActionListener e){
        unggahKTPBtn.addActionListener(e);
        unggahFotoBtn.addActionListener(e);
        backBtn.addActionListener(e);
        daftarBtn.addActionListener(e);
    }
}
