/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helper.Helper;
import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author Firdaus
 */
public class Tes extends javax.swing.JPanel {

    /**
     * Creates new form Tes
     */
    private Helper helper = new Helper();
    public Tes() {
        initComponents();
    }
    
    public Tes (String image, String nama_kendaraan, LocalDate mulai, LocalDate selesai, int harga) throws Exception{
        hargaSewa.setText(helper.priceFormat(harga));
        System.out.println(helper.priceFormat(harga));
        this.image.setIcon(helper.getImage(this.image, image));
        namaKendaraan1.setText(nama_kendaraan);
        tglMulai.setText(helper.dateFormat(mulai));
        tglSelesai.setText(helper.dateFormat(selesai));
        int tgl_mulai = mulai.getDayOfMonth();
        int tgl_selesai = selesai.getDayOfMonth();
        if(tgl_selesai-tgl_mulai < 0){
            status.setText("Telah dirental");
            status.setForeground(new Color(165, 0, 0));
        }else{
            status.setText("Sedang dirental");
            status.setForeground(new Color(47, 225, 75));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        namaKendaraan1 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        tglMulai = new javax.swing.JLabel();
        tglSelesai = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        hargaSewa = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        cardPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 49, 49)));
        cardPanel.setPreferredSize(new java.awt.Dimension(805, 160));

        image.setPreferredSize(new java.awt.Dimension(135, 136));

        namaKendaraan1.setFont(new java.awt.Font("Mulish", 1, 20)); // NOI18N
        namaKendaraan1.setForeground(new java.awt.Color(49, 49, 49));
        namaKendaraan1.setText("Alphard Tipe X");

        jLabel45.setBackground(new java.awt.Color(79, 79, 79));
        jLabel45.setFont(new java.awt.Font("Mulish Medium", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(79, 79, 79));
        jLabel45.setText("Tanggal Rental      :");

        jLabel46.setFont(new java.awt.Font("Mulish Medium", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(79, 79, 79));
        jLabel46.setText("Tanggal Kembali   :");

        tglMulai.setFont(new java.awt.Font("Mulish", 1, 12)); // NOI18N
        tglMulai.setForeground(new java.awt.Color(49, 49, 49));
        tglMulai.setText("12 Januari 2021");

        tglSelesai.setFont(new java.awt.Font("Mulish", 1, 12)); // NOI18N
        tglSelesai.setForeground(new java.awt.Color(49, 49, 49));
        tglSelesai.setText("12 Januari 2021");

        jLabel47.setBackground(new java.awt.Color(79, 79, 79));
        jLabel47.setFont(new java.awt.Font("Mulish Medium", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(79, 79, 79));
        jLabel47.setText("Harga Sewa :");

        jLabel48.setBackground(new java.awt.Color(79, 79, 79));
        jLabel48.setFont(new java.awt.Font("Mulish Medium", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(79, 79, 79));
        jLabel48.setText("Status :");

        hargaSewa.setFont(new java.awt.Font("Mulish", 1, 14)); // NOI18N
        hargaSewa.setForeground(new java.awt.Color(249, 166, 32));
        hargaSewa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hargaSewa.setText("800.000,00");

        status.setFont(new java.awt.Font("Mulish", 1, 12)); // NOI18N
        status.setForeground(new java.awt.Color(47, 225, 75));
        status.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        status.setText("Sedang dirental");

        jPanel4.setBackground(new java.awt.Color(0, 63, 130));
        jPanel4.setPreferredSize(new java.awt.Dimension(125, 39));

        jLabel49.setFont(new java.awt.Font("Mulish", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Lihat Detail");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardPanelLayout.createSequentialGroup()
                        .addComponent(namaKendaraan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(17, 17, 17)
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaSewa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(cardPanelLayout.createSequentialGroup()
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(12, 12, 12)
                                .addComponent(tglMulai))
                            .addGroup(cardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tglSelesai)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardPanelLayout.createSequentialGroup()
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(hargaSewa))
                        .addGap(12, 12, 12)
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(status))
                        .addGap(57, 57, 57)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(cardPanelLayout.createSequentialGroup()
                            .addComponent(namaKendaraan1)
                            .addGap(73, 73, 73)
                            .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel45)
                                .addComponent(tglMulai))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel46)
                                .addComponent(tglSelesai)))
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel hargaSewa;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel namaKendaraan1;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tglMulai;
    private javax.swing.JLabel tglSelesai;
    // End of variables declaration//GEN-END:variables

    

}
